### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-backend#1]
Architecture overview: https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

- [x] 1. Set up Amazon SES for Auth Flow (DevOps)
  - https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html#verify-email-addresses-procedure
- [x] 2. Set up Code Pipeline for automated SAM deployment (DevOps)
  - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
- [x] 3. Adapt authoriser to only allow SPF & HTX emails

**Comment by bearpolar** [comment]
i will try to work on the 2nd task - setting up the code pipeline.

**Comment by madanalogy** [comment]
> i will try to work on the 2nd task - setting up the code pipeline.

You will probably need to commit a `buildspec.yml` file to the repo. Can try the branching workflow we previously discussed https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Comment by madanalogy** [comment]
@ngwhhtx can you try taking on the first task? Getting SES up and running

**Comment by ngwhhtx** [comment]
> @ngwhhtx can you try taking on the first task? Getting SES up and running

Yup sure getting on it.

**Comment by madanalogy** [comment]
All tasks completed, continuous delivery using GitHub Actions instead of CodePipeline
