### ISSUE TITLE
Alpha Release Checklist

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-backend#2]
- [x] Continuous deployment of SAM application #1 
- [x] Auth Flow with Cognito and Lambda triggers #1 
- [x] REST API via AWS API Gateway #3 
- [x] Functional feature endpoints: URL-To-PDF and Instagram #3
